# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:43:14+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, RootModel


class News(BaseModel):
    Author: Optional[str] = None
    Categories: Optional[str] = None
    Content: Optional[str] = None
    NewsID: Optional[int] = None
    OriginalSource: Optional[str] = None
    OriginalSourceUrl: Optional[str] = None
    PlayerID: Optional[int] = None
    PlayerID2: Optional[int] = None
    Source: Optional[str] = None
    Team: Optional[str] = None
    Team2: Optional[str] = None
    TeamID: Optional[int] = None
    TeamID2: Optional[int] = None
    TermsOfUse: Optional[str] = None
    TimeAgo: Optional[str] = None
    Title: Optional[str] = None
    Updated: Optional[str] = None
    Url: Optional[str] = None


class FieldFormatRotoBallerPremiumNewsGetResponse(RootModel[List[News]]):
    root: List[News]


class Format(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatRotoBallerPremiumNewsByDateDateGetResponse(RootModel[List[News]]):
    root: List[News]


class FieldFormatRotoBallerPremiumNewsByPlayerIDPlayeridGetResponse(
    RootModel[List[News]]
):
    root: List[News]


class FieldFormatRotoBallerPremiumNewsByTeamTeamGetResponse(RootModel[List[News]]):
    root: List[News]
